#!/bin/bash
#tmux session chooser
#type tses to list all tmux session
#type tses followed by a number to go into that session

if [ "$1" == "" ]; then
  tmux list-sessions
else
  tmux attach -t $1
fi
